//
//  CloudLogicAPIFactory.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import AWSCore

class CloudLogicAPIFactory {
    static var supportedCloudLogicAPIs: [CloudLogicAPI] {
        
        return [
            CloudLogicAPI(displayName: "GetTwilioToken",
                apiDescription: "",
                paths: [
                 "/token", "/token/123",                ],
                endPoint: "https://big2n6ay7g.execute-api.us-east-1.amazonaws.com/acs/token",
                apiClient: AWSAPI_SQOF6EIKKL_GetTwilioTokenMobileHubClient.init(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
        ]
    }
}
