//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_hAAu4bPzA"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "6eo4m0r42qh711ju92t7lk7es5"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .USEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "1upfhc9d0ab4h06mhqdbg23llkec1rkenbkpt18ovgs5a1oq6tbg"

// Identifier for Cloud Logic API invocation clients
let AWSCloudLogicDefaultConfigurationKey: String = "CloudLogicAPIKey"
let AWSCloudLogicDefaultRegion: AWSRegionType = .USEast1
